language: java
jdk:
#  - openjdk7  #It seems openjdk temp fail on Travis
  - oraclejdk7
install: true
after_success:
  - mvn clean test org.jacoco:jacoco-maven-plugin:report org.eluder.coveralls:coveralls-maven-plugin:report
