language: java

matrix:
  include:
  - os: linux
    dist: trusty
    jdk: openjdk7
  - os: linux
    dist: precise
    jdk: oraclejdk7
  - os: linux
    ist: trusty
    jdk: openjdk8
  - os: linux
    dist: trusty
    jdk: oraclejdk8

install: true
after_success:
  - mvn clean verify org.jacoco:jacoco-maven-plugin:report org.eluder.coveralls:coveralls-maven-plugin:report
